apiVersion: apps/v1
kind: Deployment

metadata:
  name: task-manager-backend
  namespace: task-manager

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: task-manager-backend

  template:
  
    metadata:
      labels:
        app: task-manager-backend

    spec:

      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/project-4fb80391-d579-456f-9fb/demo-cluster-repo/task-manager-backend:v1
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3000

        envFrom:
          - configMapRef:
              name: backend-config

          - secretRef:
              name: backend-secret

        resources:
          requests:
            cpu: "120m"
            memory: "200Mi"

          limits:
            cpu: "240m"
            memory: "400Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 20
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 5
          periodSeconds: 5