grafana:
  enabled: true

  nodeSelector:
    workload: monitoring

  persistence:
    enabled: true
    type: pvc
    storageClassName: standard-rwo
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  grafana.ini:
    plugins:
      preinstall_auto_update: false
      
alertmanager:
  enabled: true
  alertmanagerSpec:
    nodeSelector:
      workload: monitoring

prometheusOperator:
  nodeSelector:
    workload: monitoring

kube-state-metrics:
  nodeSelector:
    workload: monitoring

prometheus:
  prometheusSpec:
    retention: 7d

    nodeSelector:
      workload: monitoring
    
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
