apiVersion: v1
kind: Service

metadata:
  name: task-manager-backend-service
  namespace: task-manager

spec:

  type: ClusterIP

  selector:
    app: task-manager-backend

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000


---


apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: task-manager-backend-hpa
  namespace: task-manager

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-manager-backend

  minReplicas: 1
  maxReplicas: 2

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50