apiVersion: v1
kind: service

metadata:
  name: task-manager-backend-service
  namespace: task-manager

spec:

  type: ClusterIP

  selector:
    app: task-manager-backend

  port:
    - protocol: TCP
      port: 3000
      targetPort: 3000