apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: task-manager

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:

    metadata:
      labels:
        app: postgres

    spec:

      containers:

        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata


          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data

          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"

            limits:
              cpu: "240m"
              memory: "400Mi"

            readinessProbe:
              exec:
                command:
                  - pg_isready
                  - -U
                  - postgres
                  - -d
                  - taskdb
              initialDelaySeconds: 5
              periodSeconds: 5

            livenessProbe:
              


      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc